### ISSUE TITLE
Tilde key does not open TRACKER

### ISSUE THREAD

**Issue by burnsauce** [monome/teletype#108]
The documentation states that the tilde (~) key will open tracker mode, but it doesn't.  Instead, it displays the £ character.

#### What steps are required to reproduce the bug?
1. Press the tilde key

**Comment by samdoshi** [comment]
The `~` key used to do that, but I removed it in 2.0. It was replaced with the `<tab>` key cycling between the 3 modes, and the extra keys to jump directly to a mode.

Which docs still include the `~`?

**Comment by cmcavoy** [comment]
I added a tag to this, not sure if the wording is right. `needs documentation` is supposed to mean "things that people could work on that are just documentation." If the tag isn't clear, feel free to change it.

**Comment by burnsauce** [comment]
Reference is in docs/quickstart.md:142
