### ISSUE TITLE
comment line

### ISSUE THREAD

**Issue by tehn** [monome/teletype#14]
hot key to comment out a single line in a script

indicated with brightness change.

**Comment by etherbrooklyn** [comment]
Is this to allow, say, // comments in scripts?  That would be ignored when loading from USB?

I'd appreciate that, as I've been working on compiling all the scrips from various lllllll threads into one nice collection, and would like to add inline comments.

**Comment by genericwoods** [comment]
I believe this would be for debugging scripts when working in the Teletype itself. You could easily 'turn off' a line of code, without deleting it. At least that’s how interpreted it. @etherbrooklyn your suggestion also sounds useful in a different way, you may want to add another feature request for that.

**Comment by burnsauce** [comment]
The patch submitted has comments persist through save/load FYI.  If this is not desirable, they can be scrubbed before saving.

**Comment by jlmitch5** [comment]
@burnsauce not something that would be necessary to change in the 2.1 timeframe by any means, but my thinking is not-persisting on save would possibly be a little "safer" in terms of UX.

Consider if the user loads a script that has a single commented-out line.  Because our indication of commenting is making the line dim, it could lead to it being unclear as to _why_ the line isn't responding to a trigger.

**Comment by cmcavoy** [comment]
> @burnsauce not something that would be necessary to change in the 2.1 timeframe by any means, but my thinking is not-persisting on save would possibly be a little "safer" in terms of UX.

Doesn't this solve #104 as a by-product? Allowing comments without changing the serialization syntax (which would force a major version change on release). If we kept the `//comments` in the serialized output, we make it easier for people to post comments to their uploaded scripts on https://github.com/monome-community/teletype-codex

**Comment by cmcavoy** [comment]
I had a conversation with one of the key folks working on Teletype Codex, #104  isn't a blocker like I thought. This is a cool feature though, 👍
