### ISSUE TITLE
LAST reports in 10 ms chunks

### ISSUE THREAD

**Issue by dndrks** [monome/teletype#144]
Experienced behavior: `LAST` reports in 10 ms chunks (150, 140, 2390, etc).
Expected behavior: `LAST` reports with 1ms accuracy (153, 148, 2399, etc).

Version: 2.3 beta B537759

To reproduce:
1. set script 1 to `PN.PUSH` some `LAST` values into any pattern
2. toggle to pattern view
3. hit F1 on keyboard

**Comment by scanner-darkly** [comment]
this also applies to `TIME`. there are also 2 bugs:
- `TIME` wraps to negative values
- `TIME.ACT` set to 0 will also stop `LAST`

both are fixed by commit c29a046.
