### ISSUE TITLE
CV output calibration

### ISSUE THREAD

**Issue by tehn** [monome/teletype#145]
in the case of CV channels not matching it'd be helpful to have a command that stores a calibration value to flash (and is automatically used in future bootups)

ie `CV.CAL 1 100` which has the effect of an additional offset.

**Comment by gssjr** [comment]
+1

**Comment by dndrks** [comment]
+1 via support

**Comment by Dewb** [comment]
I have ann [incomplete implementation](https://github.com/dewb/teletype/tree/dewb/calibration) of the calibration op strategy [proposed here](https://llllllll.co/t/teletype-cv-calibration/5654/21); I got stuck on deciding exactly where the calibration data should be stored.
