### ISSUE TITLE
Rotate screen and input/output numbers

### ISSUE THREAD

**Issue by scanner-darkly** [monome/teletype#162]
It could be useful to have an op and/or keyboard shortcut to rotate the screen and input/output number assignments 180 degrees, so that teletype could be mounted upside down.

The setting should be saved to flash.

**Comment by tehn** [comment]
i think this makes sense.

i should post up the faceplate file so someone can create an upside-down version.

heads up that i just submitted this: https://github.com/monome/libavr32/pull/39
