### ISSUE TITLE
additional PN ops, playhead per pattern

### ISSUE THREAD

**Issue by tehn** [monome/teletype#18]
PN.PUSH
PN.POP

PN.HERE
PN.NEXT

talk of P.ALL.NEXT (or similar)

this raises issues about the behavior of normal "working pattern" P.NEXT etc. values will get overwritten at some point-- is working pattern preserved? or the individual pattern's data?

my initial take: "working pattern" is floating data. individual patterns preserved.

**Comment by samdoshi** [comment]
Fixed in #73
