### ISSUE TITLE
Addressing Ansible thru hardware OPs (CV, TR, etc.) is undocumented

### ISSUE THREAD

**Issue by desolationjones** [monome/teletype#209]
From 1.2 changelog: "NEW: Ansible support added to ops: CV, CV.OFF, CV.SET, CV.SLEW, STATE, TR, TR.POL, TR.PULSE, TR.TIME, TR.TOG"

No further description of this Ansible support exists in the manual.

**Comment by scanner-darkly** [comment]
this refers to using ansible as teletype expander: https://monome.org/docs/ansible/teletype/
