### ISSUE TITLE
tele_var_t: void (*func)(uint8_t);

### ISSUE THREAD

**Issue by samdoshi** [monome/teletype#21]
In `tele_var_t` the function pointer `func` is defined as:

``` c
void (*func)(uint8_t);
```

What's the `uint8_t` argument for? The only place `func` is called is [here](https://github.com/monome/teletype/blob/master/src/teletype.c#L1563). None of the `v_*` functions make use of the `n` argument.

Shall I get rid of it and submit a PR?

**Comment by tehn** [comment]
certainly!
