### ISSUE TITLE
Update README with dev instructions.

### ISSUE THREAD

**Issue by pq** [monome/teletype#22]
It would be great if there were build instructions in the `README`.

**Comment by pq** [comment]
One gotcha worth capturing: if you don't clone with `--recursive` you'll be missing the `libavr32` submodule....

**Comment by tehn** [comment]
@samdoshi just wrote up a great tutorial here:

https://github.com/monome/libavr32

i'll get a link up on each module's readme

**Comment by pq** [comment]
Fantastic.  Thanks @tehn and @samdoshi!

**Comment by samdoshi** [comment]
@pq if anything doesn't make sense or is wrong please let me know and I'll try and get it corrected.

**Comment by pq** [comment]
Good deal. Thanks @samdoshi!
