### ISSUE TITLE
LAST n is broken for script 1

### ISSUE THREAD

**Issue by cristianvogel** [monome/teletype#222]
doesn't seem to time since a specific script ran anymore, only time since INIT script was run
Confirmed by two users using latest build... 

https://llllllll.co/t/teletype-3-2-feature-requests-and-discussions/32052/170

possibly related to this `FIX: LAST SCRIPT in live mode gives time since init script was run`

**Comment by scanner-darkly** [comment]
only affected script 1

**Comment by scanner-darkly** [comment]
fixed in CB56E83, closing.
