### ISSUE TITLE
ambiguous release statement

### ISSUE THREAD

**Issue by eeweegh** [monome/teletype#229]
#### Please describe the bug.

A silly language thing: releases clearly state that you must back up your scripts, then say 'Includes default scenes'. That made me think that I could just install a recent release into a teletype still sporting the default scenes :-) As if the default scenes were 'included' in the release.

#### Please include the hash displayed at startup and the release of the software (e.g. "Teletype v2.0.1 5f838c9")

3.2.0, but probably applicable to any release

#### What steps are required to reproduce the bug?
just install a new release without bothering about the scrip

**Comment by tehn** [comment]
fixed release file to include default scenes
