### ISSUE TITLE
v3.2.0 CTRL and PARAM editing doesn‘t work in tracker mode...

### ISSUE THREAD

**Issue by modularev** [monome/teletype#232]
... whereas CTRL + SHIFT + PARAM works. Tried with two different Keyboards.

**Comment by modularev** [comment]
https://monome.org/docs/teletype/studies-5/

under editing for values from 0-31, I quickly glanced over the changelog and found that it was changed to ctrl-alt in 3.0. I thought that I tried different combinations, but will try again.

**Comment by scanner-darkly** [comment]
thanks for updating the doc!
