### ISSUE TITLE
M.RESET is required when updating metro rate

### ISSUE THREAD

**Issue by scanner-darkly** [monome/teletype#291]
#### Please describe the bug.

when metro rate is changed and the remaining time is longer than the new interval, it will set the remaining time to the interval, so the next time it triggers exactly after the specified interval, as expected. but if the remaining time is shorter it will allow it to complete before using the new interval, resulting in having to also execute `M.RESET` in order to use the new interval immediately.

#### Please include the hash displayed at startup and the release of the software (e.g. "Teletype v2.0.1 5f838c9")

this is still a bug as of 4.0 release

#### What steps are required to reproduce the bug?
1. set metro rate to 1 sec and output a trigger on each metro tick
2. change metro rate to 2 sec when it's in the 2nd half of the metro interval

actual result: it will finish the remaining interval before using the new 2 sec interval
expected result: it should apply the new interval immediately

**Comment by desolationjones** [comment]
Can we close this issue now?
