### ISSUE TITLE
Disallow SCENE in I scripts

### ISSUE THREAD

**Issue by samdoshi** [monome/teletype#35]
This is a hypothetical failure, I haven't actually tested it.

It would be possible to create an infinite loop of `SCENE` loads, if those loads are trigger by the `I` script on scene load (or any script that it calls).

We should prevent `SCENE` running when the `I` script is triggered on load, but not when `I` is running via `SCRIPT` and a manual trigger.

I think the way I'd implement this is to modify the execution state / context to include a member `is_scene_initialising` and use that to prevent any actions we don't want run.

**Comment by tehn** [comment]
good thinking. i certainly had not considered this.
