### ISSUE TITLE
Should variables be initialised on SCENE load?

### ISSUE THREAD

**Issue by samdoshi** [monome/teletype#36]
At the moment variables stay at the previously set value when switching scenes. Should they?

You don't have enough lines in the `I` script to initialise all of them.

**Comment by samdoshi** [comment]
The other option is to save the current value for all variables in the preset

**Comment by tehn** [comment]
saving the variable state in the scene seems like it introduces some
obfuscation as to how a scene works. i'd rather have things be set in INIT.

but yes, there's only 6 lines (can be more by using dummy scripts or
eventually timeline).

perhaps we should introduce `CLEAR` which would zero out runtime variables.

note that the pattern data is considered separate and is indeed stored with
scenes.

**Comment by burnsauce** [comment]
How about a Variables screen that can both serve as a live view and a method to initialize variables?

My init scripts are crowded enough as it is, and live view was already on my radar.

**Comment by tehn** [comment]
TL (timeline) is a possible solution for this.

designing value-preset systems is tricky business-- i wouldn't suggest we save them in scenes or use live view/etc.
