### ISSUE TITLE
Bug with O?

### ISSUE THREAD

**Issue by samdoshi** [monome/teletype#37]
On a freshly booted up Teletype...
```
O        prints 1
O 0
O        prints 1
```
The docs indicate that it should return a 0. Want me to fix it?

**Comment by tehn** [comment]
certainly. perhaps the increment is happening before return?

**Comment by samdoshi** [comment]
It is, I just wanted to check which was wrong, the docs or the implementation.

How do you feel about renaming `O.DIR` to `O.INC` to indicate that it can have values other that `-1` and `1`?

I'll update the changelog if I make the change.

**Comment by tehn** [comment]
INC makes more sense, agreed.

i think post-increment is also more understandable.

**Comment by samdoshi** [comment]
Also spotted that `FLIP` was using `V_O`:

```c
static void v_FLIP() {
    if (left || top == 0) {
        push(tele_vars[V_O].v);
        tele_vars[V_O].v = (tele_vars[V_O].v == 0);
    }
    else {
        tele_vars[V_O].v = (pop() != 0);
    }
}
```

**Comment by tehn** [comment]
good catch!

**Comment by samdoshi** [comment]
`FLIP` fixed
https://github.com/samdoshi/teletype/commit/048559fa91ec6a3f4f80cdad239373586880bc4e

**Comment by samdoshi** [comment]
`O` fixed
https://github.com/samdoshi/teletype/commit/06b79a3923376af12dcd176b8d9d34961eba9fef

**Comment by samdoshi** [comment]
`O.DIR` renamed to `O.INC`
https://github.com/samdoshi/teletype/commit/a757a0c7b497fab5a0e8e47675d4fbd2615e0557

That's everything on this ticket, so I'm closing it

**Comment by samdoshi** [comment]
Have also updated `DRUNK` to follow the same semantics (as per the docs)

> DRUNK changes by -1, 0, or 1 upon each read, saving its state. Setting DRUNK will give it a new value for the next read, and drunkedness will continue on from there with subsequent reads.

https://github.com/samdoshi/teletype/commit/f720fced47edc762f5b656e49ddf08d8d1835ded
