### ISSUE TITLE
Behaviour of AVG and Q.AVG?

### ISSUE THREAD

**Issue by samdoshi** [monome/teletype#38]
At the moment `AVG` and `Q.AVG` perform integer division when calculating the average.

e.g.

```
AVG 2 3
>>> 2
```

Should they round instead?

**Comment by tehn** [comment]
i can definitely see that as being desirable!

**Comment by burnsauce** [comment]
In the PR, AVG -32767 -32768 == -32767 and AVG 32766 32767 == 32767

**Comment by burnsauce** [comment]
GNU C round() goes away from zero.

**Comment by tehn** [comment]
let's do that then.

On Tue, Sep 12, 2017 at 11:29 AM, Poindexter Frink <notifications@github.com
