### ISSUE TITLE
to_v?

### ISSUE THREAD

**Issue by samdoshi** [monome/teletype#41]
What does the `to_v` function in `teletype.c` do?

The only place it looks like it's used is in a commented out line in `main.c`.

Can I delete it?

**Comment by tehn** [comment]
it's a display function-- for taking a raw 12 bit value and printing out
voltages. it'll be useful at some point, but agreed that it's orphaned
presently.

**Comment by samdoshi** [comment]
Okay, I've renamed it to `to_voltage` and moved it to another file

https://github.com/samdoshi/teletype/commit/5d4ee63375d2b6fade776f57787f766512f8b2f9
