### ISSUE TITLE
script copy/paste

### ISSUE THREAD

**Issue by tehn** [monome/teletype#42]
hotkeys

**Comment by tehn** [comment]
suggested feature: copy-scripts-from-other-scenes. seems like it'd require a preview.

**Comment by burnsauce** [comment]
Here's an easy implementation:

- Load scene with source script
- Edit the source script
- Hotkey for copy: Ctrl-Shift-C (or something)
- Load target scene
- Edit target script
- Hotkey for paste: Ctrl-Shift-V (ditto)
