### ISSUE TITLE
BUG: Overflowing EDIT mode for Init script

### ISSUE THREAD

**Issue by barksten** [monome/teletype#45]
Version 1.1

Steps to reproduce:
1. Enter **EDIT** mode
2. Go to **I** script
3. Fill all rows (with anything, `ADD 1 1` will do)
4. Hit SHIFT+ENTER (insert row)

Expected: Noting since all rows are used.
Actual outcome: Thrown out to the tracker mode or online help mode or sometimes to write scene! Dependent on what commands that are in the buffer.

**Comment by scanner-darkly** [comment]
looks like this was fixed. i can repro with v1.1 but not with the latest code.
