### ISSUE TITLE
PREs are allowed without MODs

### ISSUE THREAD

**Issue by samdoshi** [monome/teletype#72]
As far as I can tell this bug has been there since the beginning. Or at least for quite a long time.

Consider the following

```
TR.PULSE 1 : TR.PULSE 2
```

That command doesn't make any sense as the `PRE` (i.e. before the `:`) has no `MOD` statement (e.g. `IF`). But it passes validation and runs!

What happens is the parser splits the entire command into a `PRE` and a `POST`, the validation step doesn't check to see if the first `WORD` of the `PRE` is a `MOD`. And finally the processor only executes the `PRE` (assuming that execution of the `POST` is delegated to the non-existent `MOD`).

The fix is fairly straightforward, we just need to insert a check at the end of `validate` to assert that if there is a `PRE` it must start with a `MOD`.

Unless I hear any objections I'll get it fixed in my parser branch.

**Comment by tehn** [comment]
thank you for spotting this, and the fix sounds correct.

**Comment by samdoshi** [comment]
Fixed here:

https://github.com/samdoshi/teletype/commit/e70ec4bf4eb11058f7c829706521c1e3979eb812

**Comment by samdoshi** [comment]
Fixed in #73
