### ISSUE TITLE
planck keyboard compatibility

### ISSUE THREAD

**Issue by capogreco** [monome/teletype#79]
I would love to be able to use my planck to program the teletype, but the teletype doesn't even register its existence when I plug it in.

the planck uses Atmel's Atmega32u4 AVR controller, and the firmware, as well as other information, can be found [here](https://olkb.com/reference/primer/).

I would love to help on this one, but I might need some pointers as I am a very beginner level programmer, and I'm not sure where I would even start.  any ideas?

**Comment by tehn** [comment]
does the plank display itself as a standard HID keyboard? if so it should work. if it requires any special drivers, it will not work.

**Comment by samdoshi** [comment]
I've got a Planck keyboard (need to sell it really as I don't like it). I'll try and find some time in the next few days to test mine.

**Comment by samdoshi** [comment]
Just tried my Planck and it works fine.

For your reference, it's got a REV2 PCB in it and the firmware build is probably from about 8 months ago.

**Comment by capogreco** [comment]
uggg. sorry my bad - I just installed the new firmware and hadn't power cycled the teletype. it works!

**Comment by samdoshi** [comment]
No worries @capogreco, happens to all of us...
