### ISSUE TITLE
reinstate MUTE toggle hotkeys

### ISSUE THREAD

**Issue by tehn** [monome/teletype#98]
mod+Fkeys

alt+ is jump to script
no mod is execute

how about ctrl? for usability we may want to shade the script number in EDIT mode. LIVE mode has the script-matrix-icon

**Comment by burnsauce** [comment]
Sounds good to me.  Want it in 2.1?  Sounds more like a fix than a feature.

**Comment by burnsauce** [comment]
2.1.0 implements this, but escaped the commit notes somehow.  Issue can be closed.

Script number is shaded when muted.
