### ISSUE TITLE
Duplicate commands should not append to the live command history

### ISSUE THREAD

**Issue by burnsauce** [monome/teletype#99]

**Comment by tehn** [comment]
very much agreed

**Comment by burnsauce** [comment]
Additionally, the history consumes 1056 bytes.  Is this a decent candidate for the heap?  It would reduce size on flash, and we already require malloc.

**Comment by samdoshi** [comment]
AFAIK uninitialised data doesn’t consume space in the ROM

http://samdoshi.com/post/2016/10/avr32-ram-and-rom-usage/

But I will admit that it’s all a bit confusing. Can you post the output from `avr32-objdump` and/or `avr32-size` to show that the ROM sizes does decrease.

**Comment by burnsauce** [comment]
D'oh.  Of course.  I suppose it only matters to RAM.

**Comment by scanner-darkly** [comment]
fixed in https://github.com/scanner-darkly/teletype/commit/331a537b88fa43caf69a474bdd39afbf69dc8d38
